### PR TITLE
Remove use of String class

### PR DESCRIPTION
**Pull request by billtomczak**
In php 7, String is a reserved word and cannot be used as a class name. As a result, any use of the Inflector class will break.

### CODE REVIEW

**Comment by mbabker** [comment]
This was fixed with https://github.com/joomla-framework/string/commit/185531c570abc16a80b72df6181b341aebb540a4

Also the String class can't be removed on a 1.x release.

**Comment by billtomczak** [comment]
cool. Missed that because that patch hasn't shown up in Joomla itself so far. Any way to expedite having Joomla pull the updated version?

**Comment by mbabker** [comment]
It was merged after 3.5.1 and there hasn't been a release since.  So it'll
be there next release.

**Comment by billtomczak** [comment]
Great to hear! Thanks!

**Pull request closed without merging**
