### PR TITLE
adding check for existing version of uft8_strcasecmp. 

### PR DESCRIPTION
**Pull request by pollen8**
Avoids clash when loading Joomla composer packages inside Joomla CMS

### CODE REVIEW

**Comment by mbabker** [comment]
1) As the phputf8 library is technically third party I'd rather avoid making hacks to it as much as possible, especially at the Framework level with distribution beyond the CMS.  If you really feel like these hacks are needed, dump them on the CMS.

2) Technically, you'd need this on every one of the library's functions/files.

With the last tag here in this repo, we've tried to expose all the `utf8_*` functions via `StringHelper` that map directly to PHP functions and the recommended use is to go through the `StringHelper` class versus direct loading of those functions.

**Comment by pollen8** [comment]
isn't the CMS consuming the string library as well though : libraries/vendor/joomla/string/src/... ?

**Comment by mbabker** [comment]
The CMS is consuming the library, yes.  But it also has the "old" library location (libraries/phputf8) for B/C reasons which is how the conflict can come into play.  Since the phputf8 library is abandoned and has been for several years, it isn't available as a Composer download otherwise we'd have it included as a dependency in that manner.

I'd suggest the CMS needs to update to the 1.4.0 release tag.  We actually put all the files that were being required manually in StringHelper.php into Composer's autoloader, which probably means more potential for function collisions with the "legacy" library location.  But, the CMS would then need to patch the files in library/phputf8 with the patch you've suggested here as right now it can redeclare the functions.  The full String package as distroed here can't do that and we shouldn't be adding hacks here because of the CMS currently shipping two copies of the library.

**Comment by mbabker** [comment]
Also for reference I don't believe there is anywhere in the CMS loading the functions at libraries/phputf8 anymore and if they are getting loaded then it's either a third party extension or a reference in core that needs updated still.  When we did the Composer integration we took every step practical to ensure redeclarations wouldn't happen with the core application structure, but we can't account for every possible use and we didn't want to break extensions loading the utf8 library from the old location.

**Comment by wilsonge** [comment]
I'm going to close this in favour of the issue in the CMS here https://github.com/joomla/joomla-cms/issues/9666 which is the right place to solve this

**Pull request closed without merging**
