### PR TITLE
Don't cache plurals when inflection not found

### PR DESCRIPTION
**Pull request by OSTraining**
Checking a plural word with isSingular() loads the plural into the cache as if it were singular.

To reproduce:

```
$inflector = \Joomla\String\Inflector::getInstance();
$inflector->isSingular('tags');
```

This returns `true` and leaves the cache with:

```
 [cache:Joomla\String\Inflector:private] => Array
        (
            [deer] => deer
            [moose] => moose
            [sheep] => sheep
            [bison] => bison
            [salmon] => salmon
            [pike] => pike
            [trout] => trout
            [fish] => fish
            [swine] => swine
            [alias] => aliases
            [bus] => buses
            [foot] => feet
            [goose] => geese
            [hive] => hives
            [louse] => lice
            [man] => men
            [mouse] => mice
            [ox] => oxen
            [quiz] => quizes
            [status] => statuses
            [tooth] => teeth
            [woman] => women
            [tags] => tags
        )
```

I'm not totally convinced this is the correct patch, but it does fix the problem and I've tested with the full permutations:

```
$inflector->isSingular('tags');
$inflector->isPlural('tags');
$inflector->isSingular('tag');
$inflector->isPlural('tag');
```

Note that I'm skipping the part where I reinstantiate from scratch for each test.

### CODE REVIEW

**Comment by mbabker** [comment]
At a glance this seems backward from the intent.  With your patch the values that don't match the regex are the values that get cached.

**Comment by billtomczak** [comment]
Without this patch, it uses the wrong regex and

```
$inflector->isSingular('tags');
```

causes the word 'tags' to be cached as singular. I certainly hope that is not the intent.

**Comment by mbabker** [comment]
I'll pull this down to test this week but just reading it it seems backwards from the intent, but maybe I'm also mis-reading things.

**Comment by mbabker** [comment]
You've got the right bug but the wrong fix.  Your fix does do what I suggested in that it only caches if inflection fails, not the desired behavior.

Using the `$inflector->isSingular('tags');` test case, when `$inflector->toPlural()` is called, it ultimately calls [this line](https://github.com/joomla-framework/string/blob/master/src/Inflector.php#L432) which returns `tags` (the same word it was given) so it's passing inflection from singular to plural form, is being cached, and ultimately gets returned back when `$inflector->toSingular()` is called because the value is in the cache (it's not being inflected from plural to singular).

**Comment by billtomczak** [comment]
Well, as I originally said, I wasn't 100% on my patch. I'll take a closer look and see if I can come up with something better. My solution in the meantime has been a subclass that adds the specific words I need in my extension. Not a solution I'm happy with, but it gets the job done.

To be clear, your issue is with the lack of caching in my solution, correct?

Would have been nice if the pertinent methods had been declared protected instead of private so I could more easily try some other strategies in my subclass.

**Comment by mbabker** [comment]
A PR changing the visibility isn't out of the question (making stuff more visible isn't a B/C break, it just makes it fall under more B/C rules).

> To be clear, your issue is with the lack of caching in my solution, correct?

What your solution did was to not cache inflections when a string was pluralized but it would cache if inflecting failed, and that definitely seems like a bad idea.

**Comment by billtomczak** [comment]
okay - will try again.

As for changing visibility - I would definitely advocate for that change. I'm not a fan of using private methods or properties unless there's an absolutely clear reason for them and I don't see any rationale for it here (though I'm always willing to be convinced). May I do that as a separate PR?

**Comment by mbabker** [comment]
Go for it.  Personally I default to private as it gives more flexibility on the implementation of new stuff but I start making things more visible if I start to need it in other contexts.  It seems to work OK for Symfony.

**Pull request closed without merging**
